---
- name: Configure etcd
  hosts: oo_new_etcd_to_config
  serial: 1
  any_errors_fatal: true
  vars:
    etcd_ca_host: "{{ groups.oo_etcd_to_config.0 }}"
  pre_tasks:
  - name: Add new etcd members to cluster
    command: >
      /usr/bin/etcdctl  --cert-file {{ etcd_peer_cert_file }}
                        --key-file {{ etcd_peer_key_file }}
                        --ca-file {{ etcd_peer_ca_file }}
                        -C {{ etcd_peer_url_scheme }}://{{ etcd_ca_host }}:{{ etcd_client_port }}
                        member add {{ inventory_hostname }} {{ etcd_peer_url_scheme }}://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ etcd_peer_port }}
    delegate_to: "{{ etcd_ca_host }}"
    register: etcd_add_check
  roles:
  - role: openshift_etcd
    when: etcd_add_check.rc == 0
    etcd_peers: "{{ groups.oo_etcd_to_config | union(groups.oo_new_etcd_to_config)| default([], true) }}"
    etcd_ca_host: "{{ groups.oo_etcd_to_config.0 }}"
    etcd_certificates_etcd_hosts: "{{ groups.oo_etcd_to_config | default([], true) }}"
    etcd_initial_cluster_state: "existing"
    initial_etcd_cluster: "{{ etcd_add_check.stdout_lines[3] | regex_replace('ETCD_INITIAL_CLUSTER=','') }}"
    etcd_hostname: "{{ inventory_hostname }}"
    etcd_ca_setup: False
    r_etcd_common_etcd_runtime: "{{ openshift.common.etcd_runtime }}"
  - role: nickhammond.logrotate
    when: etcd_add_check.rc == 0
