---
- import_playbook: ../../openshift-hosted/private/config.yml

- import_playbook: ../../openshift-metrics/private/config.yml
  when: openshift_metrics_install_metrics | default(false) | bool

- import_playbook: ../../openshift-logging/private/config.yml
  when: openshift_logging_install_logging | default(false) | bool

- import_playbook: ../../openshift-prometheus/private/config.yml
  when: openshift_hosted_prometheus_deploy | default(false) | bool

- import_playbook: ../../openshift-service-catalog/private/config.yml
  when: openshift_enable_service_catalog | default(false) | bool

- import_playbook: ../../openshift-management/private/config.yml
  when: openshift_management_install_management | default(false) | bool

- name: Print deprecated variable warning message if necessary
  hosts: oo_first_master
  gather_facts: no
  tasks:
  - debug: msg="{{__deprecation_message}}"
    when:
    - __deprecation_message | default ('') | length > 0
