---
- name: Assure CNI plugin config dir exists before daemon set install
  become: yes
  file: path="{{ nuage_node_plugin_dir }}" state=directory

- name: Assure CNI netconf directory exists before daemon set install
  become: yes
  file: path="{{ nuage_node_cni_netconf_dir }}" state=directory

- name: Assure CNI plugin binary directory exists before daemon set install
  become: yes
  file: path="{{ nuage_node_cni_bin_dir }}" state=directory
