---
- name: restart nuage-openshift-monitor
  become: yes
  systemd: name=nuage-openshift-monitor state=restarted

- name: restart master api
  systemd: name={{ openshift.common.service_type }}-master-api state=restarted
  when: >
    (openshift_master_ha | bool) and
    (not master_api_service_status_changed | default(false)) and
    openshift.master.cluster_method == 'native'

# TODO: need to fix up ignore_errors here
- name: restart master controllers
  systemd: name={{ openshift.common.service_type }}-master-controllers state=restarted
  when: >
    (openshift_master_ha | bool) and
    (not master_controllers_service_status_changed | default(false)) and
    openshift.master.cluster_method == 'native'
  ignore_errors: yes
