---
- name: OpenShift health checks
  hosts: oo_all_hosts
  roles:
  - openshift_health_checker
  vars:
  - r_openshift_health_checker_playbook_context: adhoc
  post_tasks:
  - name: Run health checks
    action: openshift_health_check
    args:
      checks: '{{ openshift_checks | default([]) }}'
