---
- name: Run OpenShift health checks
  hosts: oo_all_hosts
  roles:
  - openshift_health_checker
  vars:
  - r_openshift_health_checker_playbook_context: health
  post_tasks:
  - action: openshift_health_check
    args:
      checks: ['@health']
