---
# openshift_health_checker depends on openshift_version which now requires group eval.
- include: ../openshift-cluster/evaluate_groups.yml
  tags:
  - always

- name: Run OpenShift health checks
  hosts: OSEv3
  roles:
  - openshift_health_checker
  vars:
  - r_openshift_health_checker_playbook_context: "health"
  post_tasks:
  - action: openshift_health_check  # https://github.com/ansible/ansible/issues/20513
    args:
      checks: ['@health']
