---
r_nuage_master_firewall_enabled: True
r_nuage_master_use_firewalld: False

nuage_mon_rest_server_port: '9443'

r_nuage_master_os_firewall_deny: []
r_nuage_master_os_firewall_allow:
- service: openshift-monitor
  port: "{{ nuage_mon_rest_server_port }}/tcp"
