---
- name: Verify Host Requirements
  hosts: oo_all_hosts
  roles:
  - openshift_health_checker
  vars:
  - r_openshift_health_checker_playbook_context: upgrade
  post_tasks:
  - action: openshift_health_check
    args:
      checks:
      - disk_availability
      - memory_availability
