---
galaxy_info:
  author: OpenShift
  description: Openshift AWS VPC creation
  company: Red Hat, Inc
  license: ASL 2.0
  min_ansible_version: 2.3
  platforms:
  - name: EL
    versions:
    - 7
dependencies: []
