---

- name: Create temp directory for doing work in on target
  command: mktemp -td openshift-prometheus-ansible-XXXXXX
  register: mktemp
  changed_when: False

- set_fact:
    tempdir: "{{ mktemp.stdout }}"

- name: Create templates subdirectory
  file:
    state: directory
    path: "{{ tempdir }}/templates"
    mode: 0755
  changed_when: False

- include: install_prometheus.yaml
  vars:
    state: "{{ openshift_prometheus_state }}"

- name: Delete temp directory
  file:
    name: "{{ tempdir }}"
    state: absent
  changed_when: False
