---
r_openshift_aws_node_group_type: master

r_openshift_aws_node_group_config:
  tags:
    clusterid: "{{ r_openshift_aws_node_group_clusterid }}"
  master:
    instance_type: m4.xlarge
    ami: "{{ r_openshift_aws_node_group_ami }}"
    volumes:
    - device_name: /dev/sdb
      volume_size: 100
      device_type: gp2
      delete_on_termination: False
    health_check:
      period: 60
      type: EC2
    min_size: 3
    max_size: 3
    desired_size: 3
    tags:
      host-type: master
      sub-host-type: default
    wait_for_instances: True
  compute:
    instance_type: m4.xlarge
    ami: "{{ r_openshift_aws_node_group_ami }}"
    volumes:
    - device_name: /dev/sdb
      volume_size: 100
      device_type: gp2
      delete_on_termination: True
    health_check:
      period: 60
      type: EC2
    min_size: 3
    max_size: 100
    desired_size: 3
    tags:
      host-type: node
      sub-host-type: compute
  infra:
    instance_type: m4.xlarge
    ami: "{{ r_openshift_aws_node_group_ami }}"
    volumes:
    - device_name: /dev/sdb
      volume_size: 100
      device_type: gp2
      delete_on_termination: True
    health_check:
      period: 60
      type: EC2
    min_size: 2
    max_size: 20
    desired_size: 2
    tags:
      host-type: node
      sub-host-type: infra
