---
- import_playbook: validate_restart.yml

- name: Restart masters
  hosts: oo_masters_to_config
  vars:
    openshift_master_ha: "{{ groups.oo_masters_to_config | length > 1 }}"
  serial: 1
  handlers:
  - import_tasks: ../../../roles/openshift_master/handlers/main.yml
  roles:
  - openshift_facts
  post_tasks:
  - include_tasks: tasks/restart_hosts.yml
    when: openshift_rolling_restart_mode | default('services') == 'system'

  - include_tasks: tasks/restart_services.yml
    when: openshift_rolling_restart_mode | default('services') == 'services'
