---
- name: Assure CNI conf dir exists
  become: yes
  file: path="{{ cni_conf_dir }}" state=directory

- name: Assures Openshift CNI bin dir exists
  become: yes
  file: path="{{ cni_bin_dir }}" state=directory

- name: Copy the certificates and keys
  become: yes
  copy: src="/tmp/{{ item }}" dest="{{ vsp_openshift_dir }}/{{ item }}"
  with_items:
    - ca.crt
    - nuage.crt
    - nuage.key
    - nuage.kubeconfig

- include_tasks: certificates.yml

- name: Restart node services
  command: /bin/true
  notify:
    - restart node
  ignore_errors: true

- include_tasks: iptables.yml

- name: setup firewall
  import_tasks: firewall.yml
