---
- name: Install Nuage VRS
  become: yes
  yum: name={{ vrs_rpm }} state=present

- name: Set the uplink interface
  become: yes
  lineinfile: dest={{ vrs_config }} regexp=^NETWORK_UPLINK_INTF line='NETWORK_UPLINK_INTF={{ uplink_interface }}'

- name: Set the Active Controller
  become: yes
  lineinfile: dest={{ vrs_config }} regexp=^ACTIVE_CONTROLLER line='ACTIVE_CONTROLLER={{ vsc_active_ip }}'

- name: Set the K8S/OSE Cluster service CIDR
  become: yes
  lineinfile: dest={{ vrs_config }} regexp=^K8S_SERVICE_IPV4_SUBNET line='K8S_SERVICE_IPV4_SUBNET={{ k8s_cluster_service_cidr }}'

- name: Set the Standby Controller
  become: yes
  lineinfile: dest={{ vrs_config }} regexp=^STANDBY_CONTROLLER line='STANDBY_CONTROLLER={{ vsc_standby_ip }}'
  when: vsc_standby_ip is defined

- name: Install plugin rpm
  become: yes
  yum: name={{ plugin_rpm }} state=present

- name: Assure CNI conf dir exists
  become: yes
  file: path="{{ cni_conf_dir }}" state=directory

- name: Assures Openshift CNI bin dir exists
  become: yes
  file: path="{{ cni_bin_dir }}" state=directory

- name: Install CNI loopback plugin
  become: yes
  copy:
    src: "{{ k8s_cni_loopback_plugin }}"
    dest: "{{ cni_bin_dir }}/{{ k8s_cni_loopback_plugin | basename }}"
    mode: 0755

- name: Copy the certificates and keys
  become: yes
  copy: src="/tmp/{{ item }}" dest="{{ vsp_openshift_dir }}/{{ item }}"
  with_items:
    - ca.crt
    - nuage.crt
    - nuage.key
    - nuage.kubeconfig

- include: certificates.yml

- name: Set the vsp-openshift.yaml
  become: yes
  template: src=vsp-openshift.j2 dest={{ vsp_openshift_yaml }} owner=root mode=0644
  notify:
    - restart vrs
    - restart node

- include: iptables.yml

- name: setup firewall
  include: firewall.yml
  static: yes
