---
# Playbook to upgrade Docker to the max allowable version for an OpenShift cluster.
- import_playbook: ../../../../init/evaluate_groups.yml

- import_playbook: ../../../../common/openshift-cluster/upgrades/docker/docker_upgrade.yml
