---
# TODO: refactor this into its own include
# and pass a variable for ctx
- name: Verify Requirements
  hosts: oo_all_hosts
  roles:
  - openshift_health_checker
  vars:
  - r_openshift_health_checker_playbook_context: install
  post_tasks:
  - action: openshift_health_check
    args:
      checks:
      - disk_availability
      - memory_availability
      - package_availability
      - package_version
      - docker_image_availability
      - docker_storage

- include: initialize_oo_option_facts.yml
  tags:
  - always

- include: ../openshift-etcd/config.yml
  tags:
  - etcd

- include: ../openshift-nfs/config.yml
  tags:
  - nfs

- include: ../openshift-loadbalancer/config.yml
  tags:
  - loadbalancer

- include: ../openshift-master/config.yml

- include: ../openshift-node/config.yml
  tags:
  - node

- include: ../openshift-glusterfs/config.yml
  tags:
  - glusterfs

- include: openshift_hosted.yml
  tags:
  - hosted

- include: service_catalog.yml
  when:
  - openshift_enable_service_catalog | default(false) | bool
  tags:
  - servicecatalog
