---
# openshift_install_base_package_group may be set in a play variable to limit
# the host groups the base package is installed on.  This is currently used
# for master/control-plane upgrades.
- name: Set version_install_base_package true on masters and nodes
  hosts: "{{ openshift_install_base_package_group | default('oo_masters_to_config:oo_nodes_to_config') }}"
  tasks:
  - name: Set version_install_base_package true
    set_fact:
      version_install_base_package: True
    when: version_install_base_package is not defined

# NOTE: requires openshift_facts be run
- name: Determine openshift_version to configure on first master
  hosts: oo_first_master
  roles:
  - openshift_version

# NOTE: We set this even on etcd hosts as they may also later run as masters,
# and we don't want to install wrong version of docker and have to downgrade
# later.
- name: Set openshift_version for etcd, node, and master hosts
  hosts: oo_etcd_to_config:oo_nodes_to_config:oo_masters_to_config:!oo_first_master
  vars:
    openshift_version: "{{ hostvars[groups.oo_first_master.0].openshift_version }}"
  pre_tasks:
  - set_fact:
      openshift_pkg_version: -{{ openshift_version }}
    when: openshift_pkg_version is not defined
  - debug: msg="openshift_pkg_version set to {{ openshift_pkg_version }}"
  roles:
  - openshift_version
