---
- name: OpenShift Aggregated Logging
  hosts: oo_first_master
  roles:
  - openshift_logging

- name: Update Master configs
  hosts: oo_masters:!oo_first_master
  tasks:
  - block:
    - include_role:
        name: openshift_logging
        tasks_from: update_master_config
    when: openshift_logging_install_logging | default(false) | bool
