---
- include: evaluate_groups.yml
  tags:
  - always

- include: initialize_facts.yml
  tags:
  - always

- include: validate_hostnames.yml
  tags:
  - node

- include: initialize_openshift_version.yml
  tags:
  - always

- include: initialize_firewall.yml
  tags:
  - always
