---
- name: Install clients
  package:
    name: "{{ openshift_service_type }}-clients{{ openshift_pkg_version | default('') }}"
    state: present
  register: result
  until: result is succeeded

- name: Check that CLI image is present
  command: "{{ openshift_container_cli }} images -q {{ openshift_cli_image }}"
  register: cli_image

- name: Pre-pull cli image
  command: "{{ openshift_container_cli }} pull {{ openshift_cli_image }}"
  environment:
    NO_PROXY: "{{ openshift.common.no_proxy | default('') }}"
  when: cli_image.stdout_lines == []

- name: Install bash completion for oc tools
  package:
    name: bash-completion
    state: present
  register: result
  until: result is succeeded
