---


r_openshift_ami_prep_packages:
- atomic-openshift-master
- atomic-openshift-node
- atomic-openshift-docker-excluder
- atomic-openshift-sdn-ovs
- openvswitch
- docker
- etcd
#- pcs
- haproxy
- dnsmasq
- ntp
- logrotate
- httpd-tools
- bind
- firewalld
- libselinux-python
- conntrack-tools
- openssl
- cloud-init
- iproute
- python-dbus
- PyYAML
- yum-utils
- python2-boto
- python2-boto3
- cloud-utils-growpart
# gluster
- glusterfs-fuse
- heketi-client
# nfs
- nfs-utils
- flannel
- bash-completion
# cockpit
- cockpit-ws
- cockpit-system
- cockpit-bridge
- cockpit-docker
# iscsi
- iscsi-initiator-utils
# ceph
- ceph-common
# systemcontainer
# - runc
# - container-selinux
# - atomic
