---
galaxy_info:
  author: Vishal Patil
  description:
  company: Nuage Networks
  license: Apache License, Version 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
  - system
dependencies:
- role: nuage_ca
- role: nuage_common
- role: openshift_etcd_client_certificates
- role: lib_openshift
- role: lib_os_firewall
