---
# openshift_manage_node_is_master is set at the play level.
openshift_manage_node_is_master: False

# Default is to be schedulable except for master nodes.
l_openshift_manage_schedulable: "{{ openshift_schedulable | default(not openshift_manage_node_is_master) }}"
