---
- set_fact:
    openshift_release: "{{ openshift_release[1:] }}"
  when:
  - openshift_release is defined
  - openshift_release[0] == 'v'

- name: Disable all repositories
  command: subscription-manager repos --disable="*"

- name: Enable RHEL repositories
  command: subscription-manager repos \
               --enable="rhel-7-server-rpms" \
               --enable="rhel-7-server-extras-rpms" \
               --enable="rhel-7-server-ose-{{ (openshift_release | default('')).split('.')[0:2] | join('.') }}-rpms" \
               --enable="rhel-7-fast-datapath-rpms"
  register: subscribe_repos
  until: subscribe_repos | succeeded
