---
r_nuage_node_firewall_enabled: True
r_nuage_node_use_firewalld: False

nuage_mon_rest_server_port: '9443'

r_nuage_node_os_firewall_deny: []
r_nuage_node_os_firewall_allow:
- service: vxlan
  port: 4789/udp
- service: nuage-monitor
  port: "{{ nuage_mon_rest_server_port }}/tcp"
