---
os_firewall_allow:
- service: Kubernetes kubelet
  port: 10250/tcp
- service: http
  port: 80/tcp
- service: https
  port: 443/tcp
- service: OpenShift OVS sdn
  port: 4789/udp
  when: openshift.common.use_openshift_sdn | default(true) | bool
- service: Calico BGP Port
  port: 179/tcp
  when: openshift.common.use_calico | bool
