---
- name: Create the scale group
  ec2_asg:
    name: "{{ openshift_aws_scale_group_basename }} {{ item.key }}"
    launch_config_name: "{{ openshift_aws_launch_config_basename }}-{{ item.key }}{{ '-' ~ openshift_aws_new_version if openshift_aws_new_version != '' else '' }}"
    health_check_period: "{{ item.value.health_check.period }}"
    health_check_type: "{{ item.value.health_check.type }}"
    min_size: "{{ item.value.min_size }}"
    max_size: "{{ item.value.max_size }}"
    desired_capacity: "{{ item.value.desired_size }}"
    region: "{{ openshift_aws_region }}"
    termination_policies: "{{ item.value.termination_policy if 'termination_policy' in  item.value else omit }}"
    load_balancers: "{{ item.value.elbs if 'elbs' in item.value else omit }}"
    wait_for_instances: "{{ item.value.wait_for_instances | default(False)}}"
    vpc_zone_identifier: "{{ subnetout.subnets[0].id }}"
    replace_instances: "{{ openshift_aws_node_group_replace_instances if openshift_aws_node_group_replace_instances != [] else omit }}"
    replace_all_instances: "{{ omit if openshift_aws_node_group_replace_instances != [] else (item.value.replace_all_instances | default(omit)) }}"
    tags:
    - "{{ openshift_aws_node_group_config_tags | combine(item.value.tags) }}"
  with_dict: "{{ l_nodes_to_build }}"
