---
# The idea here is to wait until all scale groups are at
# their desired capacity before continuing.
- name: fetch the scale groups
  ec2_asg_facts:
    region: "{{ openshift_aws_region }}"
    tags:
      "{{ {'kubernetes.io/cluster/' ~ openshift_aws_clusterid: openshift_aws_clusterid} }}"
  register: qasg
  until: qasg.results | scale_groups_match_capacity | bool
  delay: 10
  retries: 60

- name: fetch newly created instances
  ec2_remote_facts:
    region: "{{ openshift_aws_region }}"
    filters:
      "{{ {'tag:kubernetes.io/cluster/' ~ openshift_aws_clusterid: openshift_aws_clusterid,
           'tag:version': openshift_aws_new_version} }}"
  register: instancesout
  until: instancesout.instances|length > 0
  delay: 5
  retries: 60

- name: wait for ssh to become available
  wait_for:
    port: 22
    host: "{{ item.public_ip_address }}"
    timeout: 300
    search_regex: OpenSSH
  with_items: "{{ instancesout.instances }}"
