---
- name: Wait for Node Registration
  oc_obj:
    name: "{{ l_kubelet_node_name | lower }}"
    kind: node
    state: list
  register: get_node
  until: "'metadata' in get_node.results.results[0]"
  retries: 50
  delay: 5
  when: "'nodename' in openshift.node"
  delegate_to: "{{ openshift_master_host }}"

- include_tasks: config.yml
