---
- name: Ensure bin_dir exists
  file:
    path: "{{ bin_dir }}"
    recurse: yes
    state: directory

- include_tasks: download_bins.yml

- include_tasks: netmaster.yml
  when: contiv_role == "netmaster"

- include_tasks: netplugin.yml
  when: contiv_role == "netplugin"
