---
- name: Create AWS VPC
  ec2_vpc_net:
    state: present
    cidr_block: "{{ r_openshift_aws_vpc_cidr }}"
    dns_support: True
    dns_hostnames: True
    region: "{{ r_openshift_aws_vpc_region }}"
    name: "{{ r_openshift_aws_vpc_clusterid }}"
    tags:
      Name: "{{ r_openshift_aws_vpc_clusterid }}"
  register: vpc

- name: Sleep to avoid a race condition when creating the vpc
  pause:
    seconds: 5
  when: vpc.changed

- name: assign the vpc igw
  ec2_vpc_igw:
    region: "{{ r_openshift_aws_vpc_region }}"
    vpc_id: "{{ vpc.vpc.id }}"
  register: igw

- name: assign the vpc subnets
  ec2_vpc_subnet:
    region: "{{ r_openshift_aws_vpc_region }}"
    vpc_id: "{{ vpc.vpc.id }}"
    cidr: "{{ item.cidr }}"
    az: "{{ item.az }}"
    resource_tags:
      Name: "{{ item.az }}"
  with_items: "{{ r_openshift_aws_vpc_subnets[r_openshift_aws_vpc_region] }}"

- name: Grab the route tables from our VPC
  ec2_vpc_route_table_facts:
    region: "{{ r_openshift_aws_vpc_region }}"
    filters:
      vpc-id: "{{ vpc.vpc.id }}"
  register: route_table

- name: update the route table in the vpc
  ec2_vpc_route_table:
    lookup: id
    route_table_id: "{{ route_table.route_tables[0].id }}"
    vpc_id: "{{ vpc.vpc.id }}"
    region: "{{ r_openshift_aws_vpc_region }}"
    tags:
      Name: "{{ r_openshift_aws_vpc_name }}"
    routes:
    - dest: 0.0.0.0/0
      gateway_id: igw
  register: route_table_out
