---
r_openshift_aws_sg_sg:
  default:
    name: "{{ r_openshift_aws_sg_clusterid }}"
    desc: "{{ r_openshift_aws_sg_clusterid }} default"
    rules:
    - proto: tcp
      from_port: 22
      to_port: 22
      cidr_ip: 0.0.0.0/0
    - proto: all
      from_port: all
      to_port: all
      group_name: "{{ r_openshift_aws_sg_clusterid }}"
  master:
    name: "{{ r_openshift_aws_sg_clusterid }}_master"
    desc: "{{ r_openshift_aws_sg_clusterid }} master instances"
    rules:
    - proto: tcp
      from_port: 80
      to_port: 80
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 443
      to_port: 443
      cidr_ip: 0.0.0.0/0
  compute:
    name: "{{ r_openshift_aws_sg_clusterid }}_compute"
    desc: "{{ r_openshift_aws_sg_clusterid }} compute node instances"
  infra:
    name: "{{ r_openshift_aws_sg_clusterid }}_infra"
    desc: "{{ r_openshift_aws_sg_clusterid }} infra node instances"
    rules:
    - proto: tcp
      from_port: 80
      to_port: 80
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 443
      to_port: 443
      cidr_ip: 0.0.0.0/0
    - proto: tcp
      from_port: 30000
      to_port: 32000
      cidr_ip: 0.0.0.0/0
  etcd:
    name: "{{ r_openshift_aws_sg_clusterid }}_etcd"
    desc: "{{ r_openshift_aws_sg_clusterid }} etcd instances"
