---
r_openshift_aws_elb_health_check:
  ping_protocol: tcp
  ping_port: 443
  response_timeout: 5
  interval: 30
  unhealthy_threshold: 2
  healthy_threshold: 2

r_openshift_aws_elb_cert_arn: ''

r_openshift_aws_elb_listeners:
  master:
    external:
    - protocol: tcp
      load_balancer_port: 80
      instance_protocol: ssl
      instance_port: 443
    - protocol: ssl
      load_balancer_port: 443
      instance_protocol: ssl
      instance_port: 443
      # ssl certificate required for https or ssl
      ssl_certificate_id: "{{ r_openshift_aws_elb_cert_arn }}"
    internal:
    - protocol: tcp
      load_balancer_port: 80
      instance_protocol: tcp
      instance_port: 80
    - protocol: tcp
      load_balancer_port: 443
      instance_protocol: tcp
      instance_port: 443
