---
galaxy_info:
  author: Tim Bielawa
  description: Meta role around the etcd_ca role
  company: Red Hat, Inc.
  license: Apache License, Version 2.0
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
  - system
dependencies:
- role: openshift_etcd_facts
- role: etcd_ca
  when: (etcd_ca_setup | default(True) | bool)
