---
r_openshift_master_firewall_enabled: True
r_openshift_master_use_firewalld: False

openshift_node_ips: []
r_openshift_master_clean_install: false
r_openshift_master_etcd3_storage: false
r_openshift_master_os_firewall_enable: true
r_openshift_master_os_firewall_deny: []
r_openshift_master_os_firewall_allow:
- service: api server https
  port: "{{ openshift.master.api_port }}/tcp"
- service: api controllers https
  port: "{{ openshift.master.controllers_port }}/tcp"
- service: skydns tcp
  port: "{{ openshift.master.dns_port }}/tcp"
- service: skydns udp
  port: "{{ openshift.master.dns_port }}/udp"
- service: etcd embedded
  port: 4001/tcp
  cond: "{{ groups.oo_etcd_to_config | default([]) | length == 0 }}"
