---
- name: Create our install repository
  yum_repository:
    description: "{{ item.description | default(omit) }}"
    name: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ item.gpgkey | default(omit)}}"
    gpgcheck: "{{ item.gpgcheck | default(1) }}"
    sslverify: "{{ item.sslverify | default(1) }}"
    sslclientkey: "{{ item.sslclientkey | default(omit) }}"
    sslclientcert: "{{ item.sslclientcert | default(omit) }}"
    file: "{{ item.file }}"
    enabled: "{{ item.enabled }}"
  with_items: "{{ r_openshift_ami_prep_yum_repositories }}"
